# Generated by Django 6.0.7 on 2026-07-17 14:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('pickup_address', models.CharField(max_length=255)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('pickup_contact_name', models.CharField(max_length=100)),
                ('pickup_contact_phone', models.CharField(max_length=20)),
                ('pickup_instructions', models.TextField(blank=True, null=True)),
                ('dropoff_address', models.CharField(max_length=255)),
                ('dropoff_lat', models.FloatField()),
                ('dropoff_lng', models.FloatField()),
                ('dropoff_contact_name', models.CharField(max_length=100)),
                ('dropoff_contact_phone', models.CharField(max_length=20)),
                ('dropoff_instructions', models.TextField(blank=True, null=True)),
                ('package_type', models.CharField(choices=[('document', 'Document'), ('small_package', 'Small Package'), ('medium_package', 'Medium Package'), ('large_package', 'Large Package'), ('fragile', 'Fragile')], default='small_package', max_length=20)),
                ('package_weight', models.FloatField(default=1.0)),
                ('package_length', models.FloatField(default=0.0)),
                ('package_width', models.FloatField(default=0.0)),
                ('package_height', models.FloatField(default=0.0)),
                ('package_description', models.TextField(blank=True, null=True)),
                ('package_is_fragile', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('searching_rider', 'Searching Rider'), ('rider_assigned', 'Rider Assigned'), ('rider_arrived', 'Rider Arrived'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('near_destination', 'Near Destination'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('fare_base', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('fare_distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fare_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fare_surge_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('fare_promo_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fare_total', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('fare_currency', models.CharField(default='NGN', max_length=10)),
                ('payment_method', models.CharField(default='wallet', max_length=20)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('payment_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_paid_at', models.DateTimeField(blank=True, null=True)),
                ('timeline', models.JSONField(blank=True, default=list)),
                ('estimated_distance', models.FloatField(default=0.0)),
                ('estimated_duration', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_deliveries', to=settings.AUTH_USER_MODEL)),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_deliveries', to='riders.riderprofile')),
            ],
        ),
    ]
